### PR TITLE
Simplify the usage of cdata and prefix for the attribute.

### PR DESCRIPTION
**Pull request by csablons**
attributePrefix manage the void string
keepCdata is a new param config. Set to false it allow the conversion of cdata in a simple property of the node containing him.

### CODE REVIEW

**Comment by abdmob** [comment]
Hello! I've updated x2js to v1.2.0 and configuring for __cdata is available, but you can't use attributePrefix with empty string actually, because it won't be possilbe for JSON to XML (impossible to differ attributes from elements).
So I can't accept this pull like this, but thank you anyway!

**Comment by tiagomsmagalhaes** [comment]
@abdmob is it possible to explain why is impossible to differ attributes from elements?

**Comment by abdolence** [comment]
Well, if you have empty prefix for attrs and translate XML to JSON for XML like

```
<root attr='value'>
    <element>value</element>
</root>
```

you will get something like this

```
root {
  attr : 'text',
  element : 'text'
}
```

And if you wan't to translate it back to XML you can't do it because you will get:

```
<root>
    <attr>value</attr>
    <element>value</element>
</root>
```

**Comment by tiagomsmagalhaes** [comment]
@abdmob thank you for the answer. I realized that i had one XML that had only attributes and no elements and got me wondering why it happened. i think it would be useful for this answer to be on the FAQ.

**Pull request closed without merging**
