### PR TITLE
add semicolon at the end

### PR DESCRIPTION
**Pull request by pietia**
adds semicolon at the end of source code so that the file can be concatenated with other JS code.

### CODE REVIEW

**Comment by ITachiLab** [comment]
It should be merged ASAP. Lack of the semicolon truly destroys concatenation process.

**Review by ephraimkunz — APPROVED** [review]
LGTM

**Comment by XcrossD** [comment]
`TypeError: (intermediate value)(...) is not a function`
I just encountered this error in Firefox, and this is the solution. I'm writing it down here for people to see. Hopefully this gets merged soon.

**Comment by gautiermichelin** [comment]
+1

**Comment by AndryT2** [comment]
+1. Merge this, please, because some of devs includes not minified version in build. So, this cause an issue `TypeError: (intermediate value)(...) is not a function.`

**Pull request closed without merging**
